### ISSUE TITLE
Error adding SData Reference to VS2012 sln

### ISSUE THREAD

**Issue by SeanGahan** [Sage/sdata-downloads#2]
I'm getting errors adding adding SData reference; index outside bounds...

I'm using VS2012 with Update5; trying to connect to Sage100

![sdataerrorimporting](https://cloud.githubusercontent.com/assets/15079700/15053025/6bbd63f0-12b5-11e6-9c87-207ee6879ca5.png)

**Comment by darroncockram** [comment]
What Sdata provider are you adding a reference to? Are you adding a schema reference as a file or a URL?

**Comment by SeanGahan** [comment]
When I try adding the reference via uri (http://internalServer/SData/MasApp/MasContract/CompanyCode/$schema) then I receive an index error.  I looked around a bit and did find an xsd on the server in the following location: \internalServer\Sage 100 Standard\MAS90\SData\MasContract.xsd and the program adds the references, but they are wrong and the project will not compile.  Below is a copy from the following url:http://internalServer/SData/MasApp/MasContract/CompanyCode/SO_SalesOrderHeader/$schema

Thank you for you assistance.

---

[SO_SalesOrderHeader.txt](https://github.com/Sage/sdata-downloads/files/251074/SO_SalesOrderHeader.txt)

**Comment by SeanGahan** [comment]
@darroncockram Thanks for the youtube videos!

**Comment by darroncockram** [comment]
> @darroncockram Thanks for the youtube videos!

You're welcome. Hope they've helped.

**Comment by darroncockram** [comment]
The problem is that the schema you have isn't a valid Sdata schema as it's missing the targetNamespace attribute. 

You can get the code generation to complete by changing the schema declaration to something along the lines of

``` xml
<xs:schema targetNamespace="http://myserver.com/foo/2016" xmlns="" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:sdata="http://schemas.sage.com/sdata/2008/1" xmlns:sme="http://schemas.sage.com/sdata/sme/2007" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
```

However that does not mean it will work when you use it with the feeds as that namespace will not be the one used by Mas. Did that schema come directly from the instance schema from the Mas Sdata implementation?

**Comment by SeanGahan** [comment]
I have pulled this schema right from our Mas SData implementation so I have no idea why it’s not correct.  We are using Sage 100 version 2016, is it possible that something has changed in the schema?  Can I can get a copy of the schema from somewhere? 
Thank you.
