### ISSUE TITLE
When posting an order using the SDK usng foreign currency - ids increment from 1 or 0 ?

### ISSUE THREAD

**Issue by willowsconsulting** [Sage/sdata-downloads#4]
We are posting an order to sage using the SDK 
Install is set for foreign trade  ( multi currency ) 
We are sending in a 3 for euro
Sage is posting in Argentine Peso's  ( id 4 ) 

We are thinking maybe the ids internally go from 0 

Is that correct. 
Below is the summary of fields we are filling 

"store_name": "Mxxxxx",
  "store_url": "https://trade.mccabecoffee.com/",

"shipping_firstname": "Terry",
  "shipping_lastname": "xxxx",
  "shipping_company": "xxxx",
  "shipping_address_1": "xxxxxx",
  "shipping_address_2": "xxxx",
  "shipping_city": "xxxxxx",
  "shipping_postcode": "xxxx",
  "shipping_country": "Ireland",
  "shipping_country_id": "103",
  "shipping_zone": "Dublin",
  "shipping_zone_id": "1591",
currency_id": "3",
  "currency_code": "EUR",
  "currency_value": "1.00000000",

any ideas ?  

regards
Sean

**Comment by darroncockram** [comment]
Does not appear to be an SData related issue. Suggest raising diectly with the appropriate product team instead.

**Comment by willowsconsulting** [comment]
FYI 

Currency code comes out of sage as id 1 but must be passed back in as 0. 
I have had this confirmed by others this morning. 
I'll leave that here in case some one else want to google this in the future. 

regards
Sean
