### ISSUE TITLE
Version support for Sage50 Accounts v30.0+

### ISSUE THREAD

**Issue by AlbaBeds** [Sage/sdata-downloads#5]
Regarding the **Sage50AccountsSDataInstaller.msi** installation file, when can we expect the release of support for **Sage50 Accounts v30.0**?

**Comment by darroncockram** [comment]
The version currently available supports v30 already. Note if you have the 64 bit version of Accounts installed you will need to create a registry key to allow the 32 bit Sdata to pick up the location of the data. See my response to this post https://communityhub.sage.com/gb/sage-50-accounts/f/run-your-accounts-remotely/217045/sage-50-v30-64bit-sdata-and-other-apps
